services:
  - type: web
    name: movie-ranking-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - fromGroup: movie-db-settings
    healthCheckPath: /
    buildCommand: docker build -t movie-ranking-app .
    startCommand: docker run -p $PORT:8080 movie-ranking-app 